export const TEMPLATES = [
  {
    id: 1,
    category: 'ChatGPT',
    icon: '🤖',
    title: 'Expert Explainer',
    description: 'Get any topic explained like you\'re a world-class expert',
    prompt: 'You are a world-class expert in [TOPIC]. Explain [CONCEPT] in a way that is both technically accurate and easily understandable. Use analogies, real-world examples, and a step-by-step breakdown. Include common misconceptions and how to avoid them.',
    badge: '🔥 Trending',
    color: 'from-orange-950/40 to-amber-950/40',
    border: 'border-orange-500/20 hover:border-orange-500/40',
    tagColor: 'bg-orange-500/10 text-orange-300 border-orange-500/20',
  },
  {
    id: 2,
    category: 'Midjourney',
    icon: '🎨',
    title: 'Cinematic Portrait',
    description: 'Create stunning AI portrait photography',
    prompt: 'Professional portrait of [SUBJECT], golden hour lighting, 85mm f/1.4 lens, bokeh background, cinematic color grading, high detail, photorealistic, award-winning photography, 8k resolution --ar 4:5 --style raw',
    badge: '✨ Popular',
    color: 'from-pink-950/40 to-purple-950/40',
    border: 'border-pink-500/20 hover:border-pink-500/40',
    tagColor: 'bg-pink-500/10 text-pink-300 border-pink-500/20',
  },
  {
    id: 3,
    category: 'Coding',
    icon: '💻',
    title: 'Code Reviewer',
    description: 'Senior dev-level code review feedback',
    prompt: 'Act as a senior software engineer with 15+ years of experience. Review the following code for: bugs, security vulnerabilities, performance issues, code smells, and best practice violations. Provide specific line-by-line feedback with improved code examples. Code: [PASTE CODE HERE]',
    badge: '💼 Pro Dev',
    color: 'from-emerald-950/40 to-teal-950/40',
    border: 'border-emerald-500/20 hover:border-emerald-500/40',
    tagColor: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20',
  },
  {
    id: 4,
    category: 'Marketing',
    icon: '📣',
    title: 'Viral Hook Writer',
    description: 'Write scroll-stopping marketing hooks',
    prompt: 'Write 10 different high-converting marketing hooks for [PRODUCT/SERVICE] targeting [TARGET AUDIENCE]. Each hook should use a different psychological trigger (curiosity, FOMO, social proof, pain point, desire, urgency, exclusivity, controversy, humor, transformation). Format each with the trigger type labeled.',
    badge: '📈 High ROI',
    color: 'from-amber-950/40 to-orange-950/40',
    border: 'border-amber-500/20 hover:border-amber-500/40',
    tagColor: 'bg-amber-500/10 text-amber-300 border-amber-500/20',
  },
  {
    id: 5,
    category: 'SEO',
    icon: '🔍',
    title: 'SEO Article Outline',
    description: 'Create comprehensive SEO article structures',
    prompt: 'Create a comprehensive SEO article outline for the keyword "[TARGET KEYWORD]". Include: H1 tag (with keyword), meta description (160 chars), 6-8 H2 sections with H3 subsections, LSI keywords to naturally include, internal linking opportunities, FAQ section with 5 questions, and word count recommendation. Target audience: [AUDIENCE].',
    badge: '🎯 Top Rank',
    color: 'from-emerald-950/40 to-teal-950/40',
    border: 'border-emerald-500/20 hover:border-emerald-500/40',
    tagColor: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20',
  },
  {
    id: 6,
    category: 'YouTube',
    icon: '▶️',
    title: 'YouTube Script Writer',
    description: 'Complete video scripts that keep viewers watching',
    prompt: 'Write a complete YouTube video script for "[VIDEO TITLE]" (target length: [X] minutes). Include: Hook (first 30 seconds to prevent click-away), intro with channel subscribe reminder, 3-5 main content sections with transitions, pattern interrupts every 2 minutes, mid-roll ad placement, call-to-action, and outro. Use conversational language and storytelling throughout.',
    badge: '🎬 Viral',
    color: 'from-red-950/40 to-orange-950/40',
    border: 'border-red-500/20 hover:border-red-500/40',
    tagColor: 'bg-red-500/10 text-red-300 border-red-500/20',
  },
  {
    id: 7,
    category: 'Blogging',
    icon: '✍️',
    title: 'Blog Post Generator',
    description: 'Write engaging, long-form blog posts',
    prompt: 'Write a comprehensive 2000-word blog post about [TOPIC] for [TARGET AUDIENCE]. Include: compelling headline, engaging intro with a story or shocking stat, 5 main sections with actionable advice, real-world examples, expert quotes, practical tips, and a conclusion with clear CTA. Writing style: [conversational/authoritative/educational]. SEO keyword: [KEYWORD].',
    badge: '✍️ Content',
    color: 'from-teal-950/40 to-emerald-950/40',
    border: 'border-teal-500/20 hover:border-teal-500/40',
    tagColor: 'bg-teal-500/10 text-teal-300 border-teal-500/20',
  },
  {
    id: 8,
    category: 'Business',
    icon: '💼',
    title: 'Business Plan Creator',
    description: 'Generate investor-ready business plan sections',
    prompt: 'Create a professional business plan executive summary for [BUSINESS NAME], a [BUSINESS TYPE] targeting [MARKET]. Include: problem statement, solution & value proposition, target market size (TAM/SAM/SOM), business model & revenue streams, competitive advantage, go-to-market strategy, key milestones for Year 1-3, and funding requirements. Keep it concise (500 words) yet compelling for investors.',
    badge: '💰 Pitch',
    color: 'from-amber-950/40 to-orange-950/40',
    border: 'border-amber-500/20 hover:border-amber-500/40',
    tagColor: 'bg-amber-500/10 text-amber-300 border-amber-500/20',
  },
];
