'use client';

import { motion } from 'framer-motion';
import { Scale, FileCheck, AlertTriangle, HelpCircle } from 'lucide-react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const TERMS_SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    icon: <FileCheck className="w-5 h-5 text-purple-400" />,
    content: 'By accessing or using the Prompt Beast platform, websites, and prompt engineering utilities, you agree to be bound by these Terms of Service. If you do not agree to all terms and conditions, you must immediately cease all access and usage of our tools.'
  },
  {
    title: '2. User Conduct & Constraints',
    icon: <AlertTriangle className="w-5 h-5 text-purple-400" />,
    content: 'You agree not to use our generators to craft prompts that generate harmful, hateful, illegal, sexually explicit, or defamatory content. Automated scraping, continuous bot-querying, or overloading of our API server networks is strictly prohibited.'
  },
  {
    title: '3. Intellectual Property Rights',
    icon: <Scale className="w-5 h-5 text-purple-400" />,
    content: 'You retain full ownership, copyright, and distribution rights to any original prompts you generate or customize using Prompt Beast. Our platform\'s logos, styling, codebase, algorithms, and interface frameworks remain the exclusive property of Prompt Beast.'
  },
  {
    title: '4. Service Disclaimers',
    icon: <HelpCircle className="w-5 h-5 text-purple-400" />,
    content: 'Generative AI model outputs are probabilistic. Prompt Beast provides prompt architectures &quot;as-is&quot; without any warranty of correctness, safety, or fit-for-purpose. We are not responsible for any issues resulting from outputs generated by external AI providers.'
  }
];

export default function TermsPage() {
  return (
    <main className="min-h-screen hero-bg">
      <Navbar />

      <section className="mt-16 md:mt-20 py-24 px-4 container relative">
        {/* Glow */}
        <div className="absolute top-20 right-1/4 w-[500px] h-[300px] rounded-full bg-indigo-600/10 blur-[120px] pointer-events-none" />

        <div className="max-w-4xl mx-auto relative">
          {/* Header */}
          <div className="text-center mb-16">
            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="section-label mb-3"
            >
              Legal Framework
            </motion.p>
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="section-title mb-6"
            >
              Terms of Service
            </motion.h1>
            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.1 }}
              className="text-base text-white/50 max-w-2xl mx-auto leading-relaxed"
            >
              Last Updated: May 21, 2026. Rules and guidelines governing the use of Prompt Beast services and generative interfaces.
            </motion.p>
          </div>

          {/* Main Content Card */}
          <div className="glass-card p-6 md:p-10 mb-12 space-y-8">
            <div>
              <h2 className="text-lg font-bold text-white mb-4" style={{ fontFamily: 'var(--font-display, sans-serif)' }}>
                Agreement to Terms
              </h2>
              <p className="text-sm text-white/70 leading-relaxed mb-4">
                These Terms of Service constitute a legally binding agreement made between you, whether personally or on behalf of an entity (&quot;you&quot;) and Prompt Beast (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;), concerning your access to and use of the Prompt Beast website as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto.
              </p>
              <p className="text-sm text-white/70 leading-relaxed">
                We reserve the right, in our sole discretion, to make changes or modifications to these Terms of Service at any time and for any reason. We will alert you about any changes by updating the &quot;Last Updated&quot; date of these Terms of Service.
              </p>
            </div>

            <hr className="border-white/5" />

            {/* Grid of Sections */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {TERMS_SECTIONS.map((sec, idx) => (
                <div key={sec.title} className="p-6 rounded-2xl bg-white/[0.02] border border-white/[0.05] flex flex-col gap-4">
                  <div className="w-10 h-10 rounded-xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center">
                    {sec.icon}
                  </div>
                  <h3 className="text-sm font-bold text-white tracking-wide" style={{ fontFamily: 'var(--font-display, sans-serif)' }}>
                    {sec.title}
                  </h3>
                  <p className="text-xs text-white/60 leading-relaxed">
                    {sec.content}
                  </p>
                </div>
              ))}
            </div>

            <hr className="border-white/5" />

            <div>
              <h2 className="text-lg font-bold text-white mb-4" style={{ fontFamily: 'var(--font-display, sans-serif)' }}>
                5. Limitation of Liability
              </h2>
              <p className="text-sm text-white/70 leading-relaxed">
                In no event shall Prompt Beast, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.
              </p>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
